namespace RacerData.iRacing.TelemetrySdk
{
    public interface ITelemetryFrame
    {
        #region properties

        double SessionTime { get; set; }
        int SessionTick { get; set; }
        int SessionNum { get; set; }
        int SessionState { get; set; }
        int SessionUniqueID { get; set; }
        double SessionTimeRemain { get; set; }
        int SessionLapsRemain { get; set; }
        int SessionLapsRemainEx { get; set; }
        float SessionTimeOfDay { get; set; }
        bool DriverMarker { get; set; }
        bool PushToPass { get; set; }
        bool ManualBoost { get; set; }
        bool ManualNoBoost { get; set; }
        bool IsOnTrack { get; set; }
        float FrameRate { get; set; }
        float CpuUsageBG { get; set; }
        int PlayerCarPosition { get; set; }
        int PlayerCarClassPosition { get; set; }
        int PlayerTrackSurface { get; set; }
        int PlayerTrackSurfaceMaterial { get; set; }
        int PlayerCarIdx { get; set; }
        int PlayerCarTeamIncidentCount { get; set; }
        int PlayerCarMyIncidentCount { get; set; }
        int PlayerCarDriverIncidentCount { get; set; }
        float PlayerCarWeightPenalty { get; set; }
        float PlayerCarTowTime { get; set; }
        bool PlayerCarInPitStall { get; set; }
        int PlayerCarPitSvStatus { get; set; }
        bool OnPitRoad { get; set; }
        float SteeringWheelAngle { get; set; }
        float Throttle { get; set; }
        float Brake { get; set; }
        float Clutch { get; set; }
        int Gear { get; set; }
        float RPM { get; set; }
        int Lap { get; set; }
        int LapCompleted { get; set; }
        float LapDist { get; set; }
        float LapDistPct { get; set; }
        int LapBestLap { get; set; }
        float LapBestLapTime { get; set; }
        float LapLastLapTime { get; set; }
        float LapCurrentLapTime { get; set; }
        int LapLasNLapSeq { get; set; }
        float LapLastNLapTime { get; set; }
        int LapBestNLapLap { get; set; }
        float LapBestNLapTime { get; set; }
        float LapDeltaToBestLap { get; set; }
        float LapDeltaToBestLap_DD { get; set; }
        bool LapDeltaToBestLap_OK { get; set; }
        float LapDeltaToOptimalLap { get; set; }
        float LapDeltaToOptimalLap_DD { get; set; }
        bool LapDeltaToOptimalLap_OK { get; set; }
        float LapDeltaToSessionBestLap { get; set; }
        float LapDeltaToSessionBestLap_DD { get; set; }
        bool LapDeltaToSessionBestLap_OK { get; set; }
        float LapDeltaToSessionOptimalLap { get; set; }
        float LapDeltaToSessionOptimalLap_DD { get; set; }
        bool LapDeltaToSessionOptimalLap_OK { get; set; }
        float LapDeltaToSessionLastlLap { get; set; }
        float LapDeltaToSessionLastlLap_DD { get; set; }
        bool LapDeltaToSessionLastlLap_OK { get; set; }
        float Speed { get; set; }
        float Yaw { get; set; }
        float YawNorth { get; set; }
        float Pitch { get; set; }
        float Roll { get; set; }
        int EnterExitReset { get; set; }
        double Lat { get; set; }
        double Lon { get; set; }
        float Alt { get; set; }
        float TrackTemp { get; set; }
        float TrackTempCrew { get; set; }
        float AirTemp { get; set; }
        int WeatherType { get; set; }
        int Skies { get; set; }
        float AirDensity { get; set; }
        float AirPressure { get; set; }
        float WindVel { get; set; }
        float WindDir { get; set; }
        float RelativeHumidity { get; set; }
        float FogLevel { get; set; }
        bool PitsOpen { get; set; }
        float PitRepairLeft { get; set; }
        float PitOptRepairLeft { get; set; }
        bool IsOnTrackCar { get; set; }
        float SteeringWheelPctTorque { get; set; }
        float SteeringWheelPctTorqueSign { get; set; }
        float SteeringWheelPctTorqueSignStops { get; set; }
        float SteeringWheelPctDamper { get; set; }
        float SteeringWheelAngleMax { get; set; }
        float ShiftIndicatorPct { get; set; }
        float ShiftPowerPct { get; set; }
        float ShiftGrindRPM { get; set; }
        float ThrottleRaw { get; set; }
        float BrakeRaw { get; set; }
        float HandbrakeRaw { get; set; }
        byte EngineWarnings { get; set; }
        float FuelLevel { get; set; }
        float FuelLevelPct { get; set; }
        byte PitSvFlags { get; set; }
        float PitSvLFP { get; set; }
        float PitSvRFP { get; set; }
        float PitSvLRP { get; set; }
        float PitSvRRP { get; set; }
        float PitSvFuel { get; set; }
        float TireLF_RumblePitch { get; set; }
        float TireRF_RumblePitch { get; set; }
        float TireLR_RumblePitch { get; set; }
        float TireRR_RumblePitch { get; set; }
        float SteeringWheelTorque { get; set; }
        float VelocityZ { get; set; }
        float VelocityY { get; set; }
        float VelocityX { get; set; }
        float YawRate { get; set; }
        float PitchRate { get; set; }
        float RollRate { get; set; }
        float VertAccel { get; set; }
        float LatAccel { get; set; }
        float LongAccel { get; set; }
        bool dcStarter { get; set; }
        float dpRTireChange { get; set; }
        float dpLTireChange { get; set; }
        float dpFuelFill { get; set; }
        float dpWindshieldTearoff { get; set; }
        float dpFuelAddKg { get; set; }
        float dpFastRepair { get; set; }
        float dcBrakeBias { get; set; }
        float dpRFTireColdPress { get; set; }
        float dpLFTireColdPress { get; set; }
        float dpRRTireColdPress { get; set; }
        float dpLRTireColdPress { get; set; }
        float WaterTemp { get; set; }
        float WaterLevel { get; set; }
        float FuelPress { get; set; }
        float FuelUsePerHour { get; set; }
        float OilTemp { get; set; }
        float OilPress { get; set; }
        float OilLevel { get; set; }
        float Voltage { get; set; }
        float ManifoldPress { get; set; }
        float RFspeed { get; set; }
        float RFpressure { get; set; }
        float RFcoldPressure { get; set; }
        float RFtempL { get; set; }
        float RFtempM { get; set; }
        float RFtempR { get; set; }
        float RFtempCL { get; set; }
        float RFtempCM { get; set; }
        float RFtempCR { get; set; }
        float RFwearL { get; set; }
        float RFwearM { get; set; }
        float RFwearR { get; set; }
        float LFspeed { get; set; }
        float LFpressure { get; set; }
        float LFcoldPressure { get; set; }
        float LFtempL { get; set; }
        float LFtempM { get; set; }
        float LFtempR { get; set; }
        float LFtempCL { get; set; }
        float LFtempCM { get; set; }
        float LFtempCR { get; set; }
        float LFwearL { get; set; }
        float LFwearM { get; set; }
        float LFwearR { get; set; }
        float RRspeed { get; set; }
        float RRpressure { get; set; }
        float RRcoldPressure { get; set; }
        float RRtempL { get; set; }
        float RRtempM { get; set; }
        float RRtempR { get; set; }
        float RRtempCL { get; set; }
        float RRtempCM { get; set; }
        float RRtempCR { get; set; }
        float RRwearL { get; set; }
        float RRwearM { get; set; }
        float RRwearR { get; set; }
        float LRspeed { get; set; }
        float LRpressure { get; set; }
        float LRcoldPressure { get; set; }
        float LRtempL { get; set; }
        float LRtempM { get; set; }
        float LRtempR { get; set; }
        float LRtempCL { get; set; }
        float LRtempCM { get; set; }
        float LRtempCR { get; set; }
        float LRwearL { get; set; }
        float LRwearM { get; set; }
        float LRwearR { get; set; }
        float RRshockDefl { get; set; }
        float RRshockVel { get; set; }
        float LRshockDefl { get; set; }
        float LRshockVel { get; set; }
        float RFshockDefl { get; set; }
        float RFshockVel { get; set; }
        float LFshockDefl { get; set; }
        float LFshockVel { get; set; }
        float LFrideHeight { get; set; }
        float RFrideHeight { get; set; }
        float LRrideHeight { get; set; }
        float RRrideHeight { get; set; }
        float CFSRrideHeight { get; set; }

        #endregion
    }
}