//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacerData.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RacerData.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112_Minus_Grey_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Minus_Grey_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112_Plus_Grey_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("_112_Plus_Grey_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://vjs.zencdn.net/7.5.4/video-js.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///
        ///    &lt;!-- If you&apos;d like to support IE8 (for Video.js versions prior to v7) --&gt;
        ///    &lt;script src=&quot;https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;audio id=&quot;live-video_html5_api&quot; class=&quot;video-js&quot; width=&apos;640&apos; height=&apos;264&apos; playsinline=&quot;playsinline&quot; preload=&quot;auto&quot; autoplay=&quot;&quot; data-setup=&quot;{}&quot; controls=&quot;&quot;&gt;
        ///        &lt;source src=&quot;&lt;#SOURCE#&gt;&quot; type=&quot;application/x-mpegURL&quot;&gt;
        ///        &lt;p cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string audioFeedTemplate {
            get {
                return ResourceManager.GetString("audioFeedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap headerHighlight {
            get {
                object obj = ResourceManager.GetObject("headerHighlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;No Channel Selected&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#000000&quot; text=&quot;#ffffff&quot;&gt;
        ///    &lt;p&gt;No Channel Selected&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string noChannelSelected {
            get {
                return ResourceManager.GetString("noChannelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://vjs.zencdn.net/7.5.4/video-js.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///
        ///    &lt;!-- If you&apos;d like to support IE8 (for Video.js versions prior to v7) --&gt;
        ///    &lt;script src=&quot;https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;video id=&quot;live-video_html5_api&quot; class=&quot;video-js&quot; width=&apos;640&apos; height=&apos;264&apos; playsinline=&quot;playsinline&quot; preload=&quot;auto&quot; autoplay=&quot;&quot; data-setup=&quot;{}&quot; crossorigin=&quot;anonymous&quot; muted=&quot;muted&quot; tabindex=&quot;-1&quot; src=&quot;blob:https://www.nascar.com/802ddf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string videoFeedTemplate {
            get {
                return ResourceManager.GetString("videoFeedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://vjs.zencdn.net/7.5.4/video-js.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///
        ///    &lt;!-- If you&apos;d like to support IE8 (for Video.js versions prior to v7) --&gt;
        ///    &lt;script src=&quot;https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;#VIDEOELEMENT#&gt;
        ///    &lt;script src=&apos;https://vjs.zencdn.net/7.5.4/video.js&apos;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string videoFeedTemplate2 {
            get {
                return ResourceManager.GetString("videoFeedTemplate2", resourceCulture);
            }
        }
    }
}
