namespace RacerData.iRacing.Telemetry.Sdk.Models
{
    internal class TelemetryFrame : ITelemetryFrame
    {
        #region properties

        public double SessionTime { get; set; }
        public int SessionTick { get; set; }
        public int SessionNum { get; set; }
        public irsdk_SessionState SessionState { get; set; }
        public int SessionUniqueID { get; set; }
        public double SessionTimeRemain { get; set; }
        public int SessionLapsRemain { get; set; }
        public int SessionLapsRemainEx { get; set; }
        public float SessionTimeOfDay { get; set; }
        public bool DriverMarker { get; set; }
        public bool PushToPass { get; set; }
        public bool ManualBoost { get; set; }
        public bool ManualNoBoost { get; set; }
        public bool IsOnTrack { get; set; }
        public float FrameRate { get; set; }
        public float CpuUsageBG { get; set; }
        public int PlayerCarPosition { get; set; }
        public int PlayerCarClassPosition { get; set; }
        public irsdk_TrkLoc PlayerTrackSurface { get; set; }
        public irsdk_TrkSurf PlayerTrackSurfaceMaterial { get; set; }
        public int PlayerCarIdx { get; set; }
        public int PlayerCarTeamIncidentCount { get; set; }
        public int PlayerCarMyIncidentCount { get; set; }
        public int PlayerCarDriverIncidentCount { get; set; }
        public float PlayerCarWeightPenalty { get; set; }
        public float PlayerCarTowTime { get; set; }
        public bool PlayerCarInPitStall { get; set; }
        public irsdk_PitSvStatus PlayerCarPitSvStatus { get; set; }
        public bool OnPitRoad { get; set; }
        public float SteeringWheelAngle { get; set; }
        public float Throttle { get; set; }
        public float Brake { get; set; }
        public float Clutch { get; set; }
        public int Gear { get; set; }
        public float RPM { get; set; }
        public int Lap { get; set; }
        public int LapCompleted { get; set; }
        public float LapDist { get; set; }
        public float LapDistPct { get; set; }
        public int LapBestLap { get; set; }
        public float LapBestLapTime { get; set; }
        public float LapLastLapTime { get; set; }
        public float LapCurrentLapTime { get; set; }
        public int LapLasNLapSeq { get; set; }
        public float LapLastNLapTime { get; set; }
        public int LapBestNLapLap { get; set; }
        public float LapBestNLapTime { get; set; }
        public float LapDeltaToBestLap { get; set; }
        public float LapDeltaToBestLap_DD { get; set; }
        public bool LapDeltaToBestLap_OK { get; set; }
        public float LapDeltaToOptimalLap { get; set; }
        public float LapDeltaToOptimalLap_DD { get; set; }
        public bool LapDeltaToOptimalLap_OK { get; set; }
        public float LapDeltaToSessionBestLap { get; set; }
        public float LapDeltaToSessionBestLap_DD { get; set; }
        public bool LapDeltaToSessionBestLap_OK { get; set; }
        public float LapDeltaToSessionOptimalLap { get; set; }
        public float LapDeltaToSessionOptimalLap_DD { get; set; }
        public bool LapDeltaToSessionOptimalLap_OK { get; set; }
        public float LapDeltaToSessionLastlLap { get; set; }
        public float LapDeltaToSessionLastlLap_DD { get; set; }
        public bool LapDeltaToSessionLastlLap_OK { get; set; }
        public float Speed { get; set; }
        public float Yaw { get; set; }
        public float YawNorth { get; set; }
        public float Pitch { get; set; }
        public float Roll { get; set; }
        public int EnterExitReset { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public float Alt { get; set; }
        public float TrackTemp { get; set; }
        public float TrackTempCrew { get; set; }
        public float AirTemp { get; set; }
        public int WeatherType { get; set; }
        public int Skies { get; set; }
        public float AirDensity { get; set; }
        public float AirPressure { get; set; }
        public float WindVel { get; set; }
        public float WindDir { get; set; }
        public float RelativeHumidity { get; set; }
        public float FogLevel { get; set; }
        public bool PitsOpen { get; set; }
        public float PitRepairLeft { get; set; }
        public float PitOptRepairLeft { get; set; }
        public bool IsOnTrackCar { get; set; }
        public float SteeringWheelPctTorque { get; set; }
        public float SteeringWheelPctTorqueSign { get; set; }
        public float SteeringWheelPctTorqueSignStops { get; set; }
        public float SteeringWheelPctDamper { get; set; }
        public float SteeringWheelAngleMax { get; set; }
        public float ShiftIndicatorPct { get; set; }
        public float ShiftPowerPct { get; set; }
        public float ShiftGrindRPM { get; set; }
        public float ThrottleRaw { get; set; }
        public float BrakeRaw { get; set; }
        public float HandbrakeRaw { get; set; }
        public irsdk_EngineWarnings EngineWarnings { get; set; }
        public float FuelLevel { get; set; }
        public float FuelLevelPct { get; set; }
        public irsdk_PitSvFlags PitSvFlags { get; set; }
        public float PitSvLFP { get; set; }
        public float PitSvRFP { get; set; }
        public float PitSvLRP { get; set; }
        public float PitSvRRP { get; set; }
        public float PitSvFuel { get; set; }
        public float TireLF_RumblePitch { get; set; }
        public float TireRF_RumblePitch { get; set; }
        public float TireLR_RumblePitch { get; set; }
        public float TireRR_RumblePitch { get; set; }
        public float SteeringWheelTorque { get; set; }
        public float VelocityZ { get; set; }
        public float VelocityY { get; set; }
        public float VelocityX { get; set; }
        public float YawRate { get; set; }
        public float PitchRate { get; set; }
        public float RollRate { get; set; }
        public float VertAccel { get; set; }
        public float LatAccel { get; set; }
        public float LongAccel { get; set; }
        public bool dcStarter { get; set; }
        public float dpRTireChange { get; set; }
        public float dpLTireChange { get; set; }
        public float dpFuelFill { get; set; }
        public float dpWindshieldTearoff { get; set; }
        public float dpFuelAddKg { get; set; }
        public float dpFastRepair { get; set; }
        public float dcBrakeBias { get; set; }
        public float dpRFTireColdPress { get; set; }
        public float dpLFTireColdPress { get; set; }
        public float dpRRTireColdPress { get; set; }
        public float dpLRTireColdPress { get; set; }
        public float WaterTemp { get; set; }
        public float WaterLevel { get; set; }
        public float FuelPress { get; set; }
        public float FuelUsePerHour { get; set; }
        public float OilTemp { get; set; }
        public float OilPress { get; set; }
        public float OilLevel { get; set; }
        public float Voltage { get; set; }
        public float ManifoldPress { get; set; }
        public float RFspeed { get; set; }
        public float RFpressure { get; set; }
        public float RFcoldPressure { get; set; }
        public float RFtempL { get; set; }
        public float RFtempM { get; set; }
        public float RFtempR { get; set; }
        public float RFtempCL { get; set; }
        public float RFtempCM { get; set; }
        public float RFtempCR { get; set; }
        public float RFwearL { get; set; }
        public float RFwearM { get; set; }
        public float RFwearR { get; set; }
        public float LFspeed { get; set; }
        public float LFpressure { get; set; }
        public float LFcoldPressure { get; set; }
        public float LFtempL { get; set; }
        public float LFtempM { get; set; }
        public float LFtempR { get; set; }
        public float LFtempCL { get; set; }
        public float LFtempCM { get; set; }
        public float LFtempCR { get; set; }
        public float LFwearL { get; set; }
        public float LFwearM { get; set; }
        public float LFwearR { get; set; }
        public float RRspeed { get; set; }
        public float RRpressure { get; set; }
        public float RRcoldPressure { get; set; }
        public float RRtempL { get; set; }
        public float RRtempM { get; set; }
        public float RRtempR { get; set; }
        public float RRtempCL { get; set; }
        public float RRtempCM { get; set; }
        public float RRtempCR { get; set; }
        public float RRwearL { get; set; }
        public float RRwearM { get; set; }
        public float RRwearR { get; set; }
        public float RRSHshockDefl { get; set; }
        public float LRspeed { get; set; }
        public float LRpressure { get; set; }
        public float LRcoldPressure { get; set; }
        public float LRtempL { get; set; }
        public float LRtempM { get; set; }
        public float LRtempR { get; set; }
        public float LRtempCL { get; set; }
        public float LRtempCM { get; set; }
        public float LRtempCR { get; set; }
        public float LRwearL { get; set; }
        public float LRwearM { get; set; }
        public float LRwearR { get; set; }
        public float RRshockDefl { get; set; }
        public float RRshockVel { get; set; }
        public float LRshockDefl { get; set; }
        public float LRshockVel { get; set; }
        public float RFshockDefl { get; set; }
        public float RFshockVel { get; set; }
        public float LFshockDefl { get; set; }
        public float LFshockVel { get; set; }
        public float LFrideHeight { get; set; }
        public float RFrideHeight { get; set; }
        public float LRrideHeight { get; set; }
        public float RRrideHeight { get; set; }
        public float CFSRrideHeight { get; set; }

        #endregion
    }
}


