//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacerData.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RacerData.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ActiveBorder&quot;:&quot;180, 180, 180&quot;,&quot;Window&quot;:&quot;255, 255, 255&quot;,&quot;ScrollBar&quot;:&quot;200, 200, 200&quot;,&quot;MenuText&quot;:&quot;0, 0, 0&quot;,&quot;MenuHighlight&quot;:&quot;51, 153, 255&quot;,&quot;MenuBar&quot;:&quot;240, 240, 240&quot;,&quot;Menu&quot;:&quot;240, 240, 240&quot;,&quot;InfoText&quot;:&quot;0, 0, 0&quot;,&quot;Info&quot;:&quot;255, 255, 225&quot;,&quot;InactiveCaptionText&quot;:&quot;0, 0, 0&quot;,&quot;InactiveCaption&quot;:&quot;191, 205, 219&quot;,&quot;InactiveBorder&quot;:&quot;244, 247, 252&quot;,&quot;HotTrack&quot;:&quot;0, 102, 204&quot;,&quot;HighlightText&quot;:&quot;255, 255, 255&quot;,&quot;Highlight&quot;:&quot;0, 120, 215&quot;,&quot;WindowFrame&quot;:&quot;100, 100, 100&quot;,&quot;GrayText&quot;:&quot;109, 109, 109&quot;,&quot;GradientActiveCaption&quot;:&quot;185, 209, 234&quot;,&quot;De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultColorsJson {
            get {
                return ResourceManager.GetString("DefaultColorsJson", resourceCulture);
            }
        }
    }
}
